package com.kansha.redirectNow.domain

import com.kansha.redirectNow.data.model.CountryDetails

val countryList = listOf(
    CountryDetails(name = "Afeganistão", flagCode = "af", countryCode = "93"),
    CountryDetails(name = "África do Sul", flagCode = "za", countryCode = "27"),
    CountryDetails(name = "Albânia", flagCode = "al", countryCode = "355"),
    CountryDetails(name = "Alemanha", flagCode = "de", countryCode = "49"),
    CountryDetails(name = "Andorra", flagCode = "ad", countryCode = "376"),
    CountryDetails(name = "Angola", flagCode = "ao", countryCode = "244"),
    CountryDetails(name = "Antígua e Barbuda", flagCode = "ag", countryCode = "1-268"),
    CountryDetails(name = "Arábia Saudita", flagCode = "sa", countryCode = "966"),
    CountryDetails(name = "Argélia", flagCode = "dz", countryCode = "213"),
    CountryDetails(name = "Argentina", flagCode = "ar", countryCode = "54"),
    CountryDetails(name = "Armênia", flagCode = "am", countryCode = "374"),
    CountryDetails(name = "Austrália", flagCode = "au", countryCode = "61"),
    CountryDetails(name = "Áustria", flagCode = "at", countryCode = "43"),
    CountryDetails(name = "Azerbaijão", flagCode = "az", countryCode = "994"),
    CountryDetails(name = "Bahamas", flagCode = "bs", countryCode = "1-242"),
    CountryDetails(name = "Bahrein", flagCode = "bh", countryCode = "973"),
    CountryDetails(name = "Bangladesh", flagCode = "bd", countryCode = "880"),
    CountryDetails(name = "Barbados", flagCode = "bb", countryCode = "1-246"),
    CountryDetails(name = "Belarus", flagCode = "by", countryCode = "375"),
    CountryDetails(name = "Bélgica", flagCode = "be", countryCode = "32"),
    CountryDetails(name = "Belize", flagCode = "bz", countryCode = "501"),
    CountryDetails(name = "Benin", flagCode = "bj", countryCode = "229"),
    CountryDetails(name = "Bermudas", flagCode = "bm", countryCode = "1-441"),
    CountryDetails(name = "Bolívia", flagCode = "bo", countryCode = "591"),
    CountryDetails(name = "Bósnia e Herzegovina", flagCode = "ba", countryCode = "387"),
    CountryDetails(name = "Botsuana", flagCode = "bw", countryCode = "267"),
    CountryDetails(name = "Brasil", flagCode = "br", countryCode = "55"),
    CountryDetails(name = "Brunei", flagCode = "bn", countryCode = "673"),
    CountryDetails(name = "Bulgária", flagCode = "bg", countryCode = "359"),
    CountryDetails(name = "Burquina Faso", flagCode = "bf", countryCode = "226"),
    CountryDetails(name = "Burundi", flagCode = "bi", countryCode = "257"),
    CountryDetails(name = "Butão", flagCode = "bt", countryCode = "975"),
    CountryDetails(name = "Cabo Verde", flagCode = "cv", countryCode = "238"),
    CountryDetails(name = "Camarões", flagCode = "cm", countryCode = "237"),
    CountryDetails(name = "Camboja", flagCode = "kh", countryCode = "855"),
    CountryDetails(name = "Canadá", flagCode = "ca", countryCode = "1"),
    CountryDetails(name = "Catar", flagCode = "qa", countryCode = "974"),
    CountryDetails(name = "Cazaquistão", flagCode = "kz", countryCode = "7"),
    CountryDetails(name = "Chade", flagCode = "td", countryCode = "235"),
    CountryDetails(name = "Chile", flagCode = "cl", countryCode = "56"),
    CountryDetails(name = "China", flagCode = "cn", countryCode = "86"),
    CountryDetails(name = "Chipre", flagCode = "cy", countryCode = "357"),
    CountryDetails(name = "Colômbia", flagCode = "co", countryCode = "57"),
    CountryDetails(name = "Comores", flagCode = "km", countryCode = "269"),
    CountryDetails(name = "Congo", flagCode = "cg", countryCode = "242"),
    CountryDetails(name = "Coreia do Norte", flagCode = "kp", countryCode = "850"),
    CountryDetails(name = "Coreia do Sul", flagCode = "kr", countryCode = "82"),
    CountryDetails(name = "Costa do Marfim", flagCode = "ci", countryCode = "225"),
    CountryDetails(name = "Costa Rica", flagCode = "cr", countryCode = "506"),
    CountryDetails(name = "Croácia", flagCode = "hr", countryCode = "385"),
    CountryDetails(name = "Cuba", flagCode = "cu", countryCode = "53"),
    CountryDetails(name = "Dinamarca", flagCode = "dk", countryCode = "45"),
    CountryDetails(name = "Djibouti", flagCode = "dj", countryCode = "253"),
    CountryDetails(name = "Dominica", flagCode = "dm", countryCode = "1-767"),
    CountryDetails(name = "Egito", flagCode = "eg", countryCode = "20"),
    CountryDetails(name = "El Salvador", flagCode = "sv", countryCode = "503"),
    CountryDetails(name = "Emirados Árabes Unidos", flagCode = "ae", countryCode = "971"),
    CountryDetails(name = "Equador", flagCode = "ec", countryCode = "593"),
    CountryDetails(name = "Eritreia", flagCode = "er", countryCode = "291"),
    CountryDetails(name = "Eslováquia", flagCode = "sk", countryCode = "421"),
    CountryDetails(name = "Eslovênia", flagCode = "si", countryCode = "386"),
    CountryDetails(name = "Espanha", flagCode = "es", countryCode = "34"),
    CountryDetails(name = "Estados Unidos", flagCode = "us", countryCode = "1"),
    CountryDetails(name = "Estônia", flagCode = "ee", countryCode = "372"),
    CountryDetails(name = "Eswatini", flagCode = "sz", countryCode = "268"),
    CountryDetails(name = "Etiópia", flagCode = "et", countryCode = "251"),
    CountryDetails(name = "Fiji", flagCode = "fj", countryCode = "679"),
    CountryDetails(name = "Filipinas", flagCode = "ph", countryCode = "63"),
    CountryDetails(name = "Finlândia", flagCode = "fi", countryCode = "358"),
    CountryDetails(name = "França", flagCode = "fr", countryCode = "33"),
    CountryDetails(name = "Gabão", flagCode = "ga", countryCode = "241"),
    CountryDetails(name = "Gâmbia", flagCode = "gm", countryCode = "220"),
    CountryDetails(name = "Gana", flagCode = "gh", countryCode = "233"),
    CountryDetails(name = "Geórgia", flagCode = "ge", countryCode = "995"),
    CountryDetails(name = "Granada", flagCode = "gd", countryCode = "1-473"),
    CountryDetails(name = "Grécia", flagCode = "gr", countryCode = "30"),
    CountryDetails(name = "Guatemala", flagCode = "gt", countryCode = "502"),
    CountryDetails(name = "Guiana", flagCode = "gy", countryCode = "592"),
    CountryDetails(name = "Guiné", flagCode = "gn", countryCode = "224"),
    CountryDetails(name = "Guiné-Bissau", flagCode = "gw", countryCode = "245"),
    CountryDetails(name = "Guiné Equatorial", flagCode = "gq", countryCode = "240"),
    CountryDetails(name = "Haiti", flagCode = "ht", countryCode = "509"),
    CountryDetails(name = "Holanda", flagCode = "nl", countryCode = "31"),
    CountryDetails(name = "Honduras", flagCode = "hn", countryCode = "504"),
    CountryDetails(name = "Hungria", flagCode = "hu", countryCode = "36"),
    CountryDetails(name = "Iêmen", flagCode = "ye", countryCode = "967"),
    CountryDetails(name = "Ilhas Marshall", flagCode = "mh", countryCode = "692"),
    CountryDetails(name = "Índia", flagCode = "in", countryCode = "91"),
    CountryDetails(name = "Indonésia", flagCode = "id", countryCode = "62"),
    CountryDetails(name = "Irã", flagCode = "ir", countryCode = "98"),
    CountryDetails(name = "Iraque", flagCode = "iq", countryCode = "964"),
    CountryDetails(name = "Irlanda", flagCode = "ie", countryCode = "353"),
    CountryDetails(name = "Islândia", flagCode = "is", countryCode = "354"),
    CountryDetails(name = "Israel", flagCode = "il", countryCode = "972"),
    CountryDetails(name = "Itália", flagCode = "it", countryCode = "39"),
    CountryDetails(name = "Jamaica", flagCode = "jm", countryCode = "1-876"),
    CountryDetails(name = "Japão", flagCode = "jp", countryCode = "81"),
    CountryDetails(name = "Jordânia", flagCode = "jo", countryCode = "962"),
    CountryDetails(name = "Kiribati", flagCode = "ki", countryCode = "686"),
    CountryDetails(name = "Kuwait", flagCode = "kw", countryCode = "965"),
    CountryDetails(name = "Laos", flagCode = "la", countryCode = "856"),
    CountryDetails(name = "Lesoto", flagCode = "ls", countryCode = "266"),
    CountryDetails(name = "Letônia", flagCode = "lv", countryCode = "371"),
    CountryDetails(name = "Líbano", flagCode = "lb", countryCode = "961"),
    CountryDetails(name = "Libéria", flagCode = "lr", countryCode = "231"),
    CountryDetails(name = "Líbia", flagCode = "ly", countryCode = "218"),
    CountryDetails(name = "Liechtenstein", flagCode = "li", countryCode = "423"),
    CountryDetails(name = "Lituânia", flagCode = "lt", countryCode = "370"),
    CountryDetails(name = "Luxemburgo", flagCode = "lu", countryCode = "352"),
    CountryDetails(name = "Madagascar", flagCode = "mg", countryCode = "261"),
    CountryDetails(name = "Malásia", flagCode = "my", countryCode = "60"),
    CountryDetails(name = "Malawi", flagCode = "mw", countryCode = "265"),
    CountryDetails(name = "Maldivas", flagCode = "mv", countryCode = "960"),
    CountryDetails(name = "Mali", flagCode = "ml", countryCode = "223"),
    CountryDetails(name = "Malta", flagCode = "mt", countryCode = "356"),
    CountryDetails(name = "Marrocos", flagCode = "ma", countryCode = "212"),
    CountryDetails(name = "Maurício", flagCode = "mu", countryCode = "230"),
    CountryDetails(name = "Mauritânia", flagCode = "mr", countryCode = "222"),
    CountryDetails(name = "México", flagCode = "mx", countryCode = "52"),
    CountryDetails(name = "Mianmar", flagCode = "mm", countryCode = "95"),
    CountryDetails(name = "Micronésia", flagCode = "fm", countryCode = "691"),
    CountryDetails(name = "Moçambique", flagCode = "mz", countryCode = "258"),
    CountryDetails(name = "Moldávia", flagCode = "md", countryCode = "373"),
    CountryDetails(name = "Mônaco", flagCode = "mc", countryCode = "377"),
    CountryDetails(name = "Mongólia", flagCode = "mn", countryCode = "976"),
    CountryDetails(name = "Montenegro", flagCode = "me", countryCode = "382"),
    CountryDetails(name = "Namíbia", flagCode = "na", countryCode = "264"),
    CountryDetails(name = "Nauru", flagCode = "nr", countryCode = "674"),
    CountryDetails(name = "Nepal", flagCode = "np", countryCode = "977"),
    CountryDetails(name = "Nicarágua", flagCode = "ni", countryCode = "505"),
    CountryDetails(name = "Níger", flagCode = "ne", countryCode = "227"),
    CountryDetails(name = "Nigéria", flagCode = "ng", countryCode = "234"),
    CountryDetails(name = "Noruega", flagCode = "no", countryCode = "47"),
    CountryDetails(name = "Nova Zelândia", flagCode = "nz", countryCode = "64"),
    CountryDetails(name = "Omã", flagCode = "om", countryCode = "968"),
    CountryDetails(name = "Palau", flagCode = "pw", countryCode = "680"),
    CountryDetails(name = "Panamá", flagCode = "pa", countryCode = "507"),
    CountryDetails(name = "Papua-Nova Guiné", flagCode = "pg", countryCode = "675"),
    CountryDetails(name = "Paquistão", flagCode = "pk", countryCode = "92"),
    CountryDetails(name = "Paraguai", flagCode = "py", countryCode = "595"),
    CountryDetails(name = "Peru", flagCode = "pe", countryCode = "51"),
    CountryDetails(name = "Polônia", flagCode = "pl", countryCode = "48"),
    CountryDetails(name = "Portugal", flagCode = "pt", countryCode = "351"),
    CountryDetails(name = "Qatar", flagCode = "qa", countryCode = "974"),
    CountryDetails(name = "Quênia", flagCode = "ke", countryCode = "254"),
    CountryDetails(name = "Reino Unido", flagCode = "gb", countryCode = "44"),
    CountryDetails(name = "República Centro-Africana", flagCode = "cf", countryCode = "236"),
    CountryDetails(name = "República Dominicana", flagCode = "do", countryCode = "1-809"),
    CountryDetails(name = "Romênia", flagCode = "ro", countryCode = "40"),
    CountryDetails(name = "Ruanda", flagCode = "rw", countryCode = "250"),
    CountryDetails(name = "Rússia", flagCode = "ru", countryCode = "7"),
    CountryDetails(name = "Samoa", flagCode = "ws", countryCode = "685"),
    CountryDetails(name = "Santa Lúcia", flagCode = "lc", countryCode = "1-758"),
    CountryDetails(name = "São Cristóvão e Nevis", flagCode = "kn", countryCode = "1-869"),
    CountryDetails(name = "São Marino", flagCode = "sm", countryCode = "378"),
    CountryDetails(name = "São Tomé e Príncipe", flagCode = "st", countryCode = "239"),
    CountryDetails(name = "São Vicente e Granadinas", flagCode = "vc", countryCode = "1-784"),
    CountryDetails(name = "Seicheles", flagCode = "sc", countryCode = "248"),
    CountryDetails(name = "Senegal", flagCode = "sn", countryCode = "221"),
    CountryDetails(name = "Serra Leoa", flagCode = "sl", countryCode = "232"),
    CountryDetails(name = "Sérvia", flagCode = "rs", countryCode = "381"),
    CountryDetails(name = "Singapura", flagCode = "sg", countryCode = "65"),
    CountryDetails(name = "Síria", flagCode = "sy", countryCode = "963"),
    CountryDetails(name = "Somália", flagCode = "so", countryCode = "252"),
    CountryDetails(name = "Sri Lanka", flagCode = "lk", countryCode = "94"),
    CountryDetails(name = "Suazilândia", flagCode = "sz", countryCode = "268"),
    CountryDetails(name = "Sudão", flagCode = "sd", countryCode = "249"),
    CountryDetails(name = "Sudão do Sul", flagCode = "ss", countryCode = "211"),
    CountryDetails(name = "Suécia", flagCode = "se", countryCode = "46"),
    CountryDetails(name = "Suíça", flagCode = "ch", countryCode = "41"),
    CountryDetails(name = "Suriname", flagCode = "sr", countryCode = "597"),
    CountryDetails(name = "Tailândia", flagCode = "th", countryCode = "66"),
    CountryDetails(name = "Taiwan", flagCode = "tw", countryCode = "886"),
    CountryDetails(name = "Tajiquistão", flagCode = "tj", countryCode = "992"),
    CountryDetails(name = "Tanzânia", flagCode = "tz", countryCode = "255"),
    CountryDetails(name = "Timor-Leste", flagCode = "tl", countryCode = "670"),
    CountryDetails(name = "Togo", flagCode = "tg", countryCode = "228"),
    CountryDetails(name = "Tonga", flagCode = "to", countryCode = "676"),
    CountryDetails(name = "Trinidad e Tobago", flagCode = "tt", countryCode = "1-868"),
    CountryDetails(name = "Tunísia", flagCode = "tn", countryCode = "216"),
    CountryDetails(name = "Turcomenistão", flagCode = "tm", countryCode = "993"),
    CountryDetails(name = "Turquia", flagCode = "tr", countryCode = "90"),
    CountryDetails(name = "Tuvalu", flagCode = "tv", countryCode = "688"),
    CountryDetails(name = "Ucrânia", flagCode = "ua", countryCode = "380"),
    CountryDetails(name = "Uganda", flagCode = "ug", countryCode = "256"),
    CountryDetails(name = "Uruguai", flagCode = "uy", countryCode = "598"),
    CountryDetails(name = "Uzbequistão", flagCode = "uz", countryCode = "998"),
    CountryDetails(name = "Vanuatu", flagCode = "vu", countryCode = "678"),
    CountryDetails(name = "Vaticano", flagCode = "va", countryCode = "379"),
    CountryDetails(name = "Venezuela", flagCode = "ve", countryCode = "58"),
    CountryDetails(name = "Vietnã", flagCode = "vn", countryCode = "84"),
    CountryDetails(name = "Zâmbia", flagCode = "zm", countryCode = "260"),
    CountryDetails(name = "Zimbábue", flagCode = "zw", countryCode = "263"),
)