package com.kansha.redirectNow.domain

import com.kansha.redirectNow.data.model.CountryDetails

val countryList = listOf(
    CountryDetails(name = "Afeganistão", flagCode = "af", countryCode = "93", mask = "##-###-####"),
    CountryDetails(name = "África do Sul", flagCode = "za", countryCode = "27", mask = "##-###-####"),
    CountryDetails(name = "Albânia", flagCode = "al", countryCode = "355", mask = "(###)###-###"),
    CountryDetails(name = "Alemanha", flagCode = "de", countryCode = "49"),
    CountryDetails(name = "Andorra", flagCode = "ad", countryCode = "376", mask = "###-###"),
    CountryDetails(name = "Angola", flagCode = "ao", countryCode = "244", mask = "(###)###-###"),
    CountryDetails(name = "Antígua e Barbuda", flagCode = "ag", countryCode = "1-268", mask = "###-####"),
    CountryDetails(name = "Arábia Saudita", flagCode = "sa", countryCode = "966", mask = "#-###-####"),
    CountryDetails(name = "Argélia", flagCode = "dz", countryCode = "213", mask = "##-###-####"),
    CountryDetails(name = "Argentina", flagCode = "ar", countryCode = "54", mask = "(###)###-####"),
    CountryDetails(name = "Armênia", flagCode = "am", countryCode = "374", mask = "##-###-###"),
    CountryDetails(name = "Austrália", flagCode = "au", countryCode = "61", mask = "#-####-####"),
    CountryDetails(name = "Áustria", flagCode = "at", countryCode = "43", mask = "(###)###-####"),
    CountryDetails(name = "Azerbaijão", flagCode = "az", countryCode = "994", mask = "##-###-##-##"),
    CountryDetails(name = "Bahamas", flagCode = "bs", countryCode = "1-242", mask = "###-####"),
    CountryDetails(name = "Bahrein", flagCode = "bh", countryCode = "973", mask = "####-####"),
    CountryDetails(name = "Bangladesh", flagCode = "bd", countryCode = "880", mask = "##-###-###"),
    CountryDetails(name = "Barbados", flagCode = "bb", countryCode = "1-246", mask = "###-####"),
    CountryDetails(name = "Belarus", flagCode = "by", countryCode = "375", mask = "(##)###-##-##"),
    CountryDetails(name = "Bélgica", flagCode = "be", countryCode = "32", mask = "(###)###-###"),
    CountryDetails(name = "Belize", flagCode = "bz", countryCode = "501", mask = "###-####"),
    CountryDetails(name = "Benin", flagCode = "bj", countryCode = "229", mask = "##-##-####"),
    CountryDetails(name = "Bermudas", flagCode = "bm", countryCode = "1-441", mask = "###-####"),
    CountryDetails(name = "Bolívia", flagCode = "bo", countryCode = "591", mask = "#-###-####"),
    CountryDetails(name = "Bósnia e Herzegovina", flagCode = "ba", countryCode = "387", mask = "##-#####"),
    CountryDetails(name = "Botsuana", flagCode = "bw", countryCode = "267", mask = "##-###-###"),
    CountryDetails(name = "Brasil", flagCode = "br", countryCode = "55", mask = "(##)#####-####"),
    CountryDetails(name = "Brunei", flagCode = "bn", countryCode = "673", mask = "###-####"),
    CountryDetails(name = "Bulgária", flagCode = "bg", countryCode = "359", mask = "(###)###-###"),
    CountryDetails(name = "Burquina Faso", flagCode = "bf", countryCode = "226", mask = "##-##-####"),
    CountryDetails(name = "Burundi", flagCode = "bi", countryCode = "257", mask = "##-##-####"),
    CountryDetails(name = "Butão", flagCode = "bt", countryCode = "975"),
    CountryDetails(name = "Cabo Verde", flagCode = "cv", countryCode = "238", mask = "(###)##-##"),
    CountryDetails(name = "Camarões", flagCode = "cm", countryCode = "237", mask = "####-####"),
    CountryDetails(name = "Camboja", flagCode = "kh", countryCode = "855", mask = "##-###-###"),
    CountryDetails(name = "Canadá", flagCode = "ca", countryCode = "1", mask = "(###)###-####"),
    CountryDetails(name = "Catar", flagCode = "qa", countryCode = "974", mask = "####-####"),
    CountryDetails(name = "Cazaquistão", flagCode = "kz", countryCode = "7", mask = "(###)###-##-##"),
    CountryDetails(name = "Chade", flagCode = "td", countryCode = "235", mask = "##-##-##-##"),
    CountryDetails(name = "Chile", flagCode = "cl", countryCode = "56", mask = "#-####-####"),
    CountryDetails(name = "China", flagCode = "cn", countryCode = "86"),
    CountryDetails(name = "Chipre", flagCode = "cy", countryCode = "357", mask = "##-###-###"),
    CountryDetails(name = "Colômbia", flagCode = "co", countryCode = "57", mask = "(###)###-####"),
    CountryDetails(name = "Comores", flagCode = "km", countryCode = "269", mask = "##-#####"),
    CountryDetails(name = "Congo", flagCode = "cg", countryCode = "242", mask = "##-###-####"),
    CountryDetails(name = "Coreia do Norte", flagCode = "kp", countryCode = "850"),
    CountryDetails(name = "Coreia do Sul", flagCode = "kr", countryCode = "82", mask = "##-###-####"),
    CountryDetails(name = "Costa do Marfim", flagCode = "ci", countryCode = "225", mask = "##-###-###"),
    CountryDetails(name = "Costa Rica", flagCode = "cr", countryCode = "506", mask = "####-####"),
    CountryDetails(name = "Croácia", flagCode = "hr", countryCode = "385", mask = "##-###-###"),
    CountryDetails(name = "Cuba", flagCode = "cu", countryCode = "53", mask = "#-###-####"),
    CountryDetails(name = "Dinamarca", flagCode = "dk", countryCode = "45", mask = "##-##-##-##"),
    CountryDetails(name = "Djibouti", flagCode = "dj", countryCode = "253", mask = "##-##-##-##"),
    CountryDetails(name = "Dominica", flagCode = "dm", countryCode = "1-767", mask = "###-####"),
    CountryDetails(name = "Egito", flagCode = "eg", countryCode = "20", mask = "(###)###-####"),
    CountryDetails(name = "El Salvador", flagCode = "sv", countryCode = "503", mask = "##-##-####"),
    CountryDetails(name = "Emirados Árabes Unidos", flagCode = "ae", countryCode = "971"),
    CountryDetails(name = "Equador", flagCode = "ec", countryCode = "593"),
    CountryDetails(name = "Eritreia", flagCode = "er", countryCode = "291", mask = "#-###-###"),
    CountryDetails(name = "Eslováquia", flagCode = "sk", countryCode = "421", mask = "(###)###-###"),
    CountryDetails(name = "Eslovênia", flagCode = "si", countryCode = "386", mask = "##-###-###"),
    CountryDetails(name = "Espanha", flagCode = "es", countryCode = "34", mask = "(###)###-###"),
    CountryDetails(name = "Estados Unidos", flagCode = "us", countryCode = "1", mask = "(###)###-####"),
    CountryDetails(name = "Estônia", flagCode = "ee", countryCode = "372"),
    CountryDetails(name = "Eswatini", flagCode = "sz", countryCode = "268", mask = "##-##-####"),
    CountryDetails(name = "Etiópia", flagCode = "et", countryCode = "251", mask = "##-###-####"),
    CountryDetails(name = "Fiji", flagCode = "fj", countryCode = "679", mask = "##-#####"),
    CountryDetails(name = "Filipinas", flagCode = "ph", countryCode = "63", mask = "(###)###-####"),
    CountryDetails(name = "Finlândia", flagCode = "fi", countryCode = "358", mask = "(###)###-##-##"),
    CountryDetails(name = "França", flagCode = "fr", countryCode = "33", mask = "(###)###-###"),
    CountryDetails(name = "Gabão", flagCode = "ga", countryCode = "241", mask = "#-##-##-##"),
    CountryDetails(name = "Gâmbia", flagCode = "gm", countryCode = "220", mask = "(###)##-##"),
    CountryDetails(name = "Gana", flagCode = "gh", countryCode = "233", mask = "(###)###-###"),
    CountryDetails(name = "Geórgia", flagCode = "ge", countryCode = "995", mask = "(###)###-###"),
    CountryDetails(name = "Granada", flagCode = "gd", countryCode = "1-473", mask = "###-####"),
    CountryDetails(name = "Grécia", flagCode = "gr", countryCode = "30", mask = "(###)###-####"),
    CountryDetails(name = "Guatemala", flagCode = "gt", countryCode = "502", mask = "#-###-####"),
    CountryDetails(name = "Guiana", flagCode = "gy", countryCode = "592", mask = "###-####"),
    CountryDetails(name = "Guiné", flagCode = "gn", countryCode = "224", mask = "##-###-###"),
    CountryDetails(name = "Guiné-Bissau", flagCode = "gw", countryCode = "245", mask = "#-######"),
    CountryDetails(name = "Guiné Equatorial", flagCode = "gq", countryCode = "240", mask = "##-###-####"),
    CountryDetails(name = "Haiti", flagCode = "ht", countryCode = "509", mask = "##-##-####"),
    CountryDetails(name = "Holanda", flagCode = "nl", countryCode = "31", mask = "##-###-####"),
    CountryDetails(name = "Honduras", flagCode = "hn", countryCode = "504", mask = "####-####"),
    CountryDetails(name = "Hungria", flagCode = "hu", countryCode = "36", mask = "(###)###-###"),
    CountryDetails(name = "Iêmen", flagCode = "ye", countryCode = "967"),
    CountryDetails(name = "Ilhas Marshall", flagCode = "mh", countryCode = "692", mask = "###-####"),
    CountryDetails(name = "Índia", flagCode = "in", countryCode = "91", mask = "(####)###-###"),
    CountryDetails(name = "Indonésia", flagCode = "id", countryCode = "62"),
    CountryDetails(name = "Irã", flagCode = "ir", countryCode = "98", mask = "(###)###-####"),
    CountryDetails(name = "Iraque", flagCode = "iq", countryCode = "964", mask = "(###)###-####"),
    CountryDetails(name = "Irlanda", flagCode = "ie", countryCode = "353", mask = "(###)###-###"),
    CountryDetails(name = "Islândia", flagCode = "is", countryCode = "354", mask = "###-####"),
    CountryDetails(name = "Israel", flagCode = "il", countryCode = "972"),
    CountryDetails(name = "Itália", flagCode = "it", countryCode = "39", mask = "(###)####-###"),
    CountryDetails(name = "Jamaica", flagCode = "jm", countryCode = "1-876", mask = "###-####"),
    CountryDetails(name = "Japão", flagCode = "jp", countryCode = "81", mask = "##-####-####"),
    CountryDetails(name = "Jordânia", flagCode = "jo", countryCode = "962", mask = "#-####-####"),
    CountryDetails(name = "Kiribati", flagCode = "ki", countryCode = "686", mask = "##-###"),
    CountryDetails(name = "Kuwait", flagCode = "kw", countryCode = "965", mask = "####-####"),
    CountryDetails(name = "Laos", flagCode = "la", countryCode = "856"),
    CountryDetails(name = "Lesoto", flagCode = "ls", countryCode = "266", mask = "#-###-####"),
    CountryDetails(name = "Letônia", flagCode = "lv", countryCode = "371", mask = "##-###-###"),
    CountryDetails(name = "Líbano", flagCode = "lb", countryCode = "961"),
    CountryDetails(name = "Libéria", flagCode = "lr", countryCode = "231", mask = "##-###-###"),
    CountryDetails(name = "Líbia", flagCode = "ly", countryCode = "218"),
    CountryDetails(name = "Liechtenstein", flagCode = "li", countryCode = "423", mask = "(###)###-####"),
    CountryDetails(name = "Lituânia", flagCode = "lt", countryCode = "370", mask = "(###)##-###"),
    CountryDetails(name = "Luxemburgo", flagCode = "lu", countryCode = "352", mask = "(###)###-###"),
    CountryDetails(name = "Madagascar", flagCode = "mg", countryCode = "261", mask = "##-##-#####"),
    CountryDetails(name = "Malásia", flagCode = "my", countryCode = "60"),
    CountryDetails(name = "Malawi", flagCode = "mw", countryCode = "265"),
    CountryDetails(name = "Maldivas", flagCode = "mv", countryCode = "960", mask = "###-####"),
    CountryDetails(name = "Mali", flagCode = "ml", countryCode = "223", mask = "##-##-####"),
    CountryDetails(name = "Malta", flagCode = "mt", countryCode = "356", mask = "####-####"),
    CountryDetails(name = "Marrocos", flagCode = "ma", countryCode = "212", mask = "##-####-###"),
    CountryDetails(name = "Maurício", flagCode = "mu", countryCode = "230", mask = "###-####"),
    CountryDetails(name = "Mauritânia", flagCode = "mr", countryCode = "222", mask = "##-##-####"),
    CountryDetails(name = "México", flagCode = "mx", countryCode = "52"),
    CountryDetails(name = "Mianmar", flagCode = "mm", countryCode = "95"),
    CountryDetails(name = "Micronésia", flagCode = "fm", countryCode = "691", mask = "###-####"),
    CountryDetails(name = "Moçambique", flagCode = "mz", countryCode = "258", mask = "##-###-###"),
    CountryDetails(name = "Moldávia", flagCode = "md", countryCode = "373", mask = "####-####"),
    CountryDetails(name = "Mônaco", flagCode = "mc", countryCode = "377"),
    CountryDetails(name = "Mongólia", flagCode = "mn", countryCode = "976", mask = "##-##-####"),
    CountryDetails(name = "Montenegro", flagCode = "me", countryCode = "382", mask = "##-###-###"),
    CountryDetails(name = "Namíbia", flagCode = "na", countryCode = "264", mask = "##-###-####"),
    CountryDetails(name = "Nauru", flagCode = "nr", countryCode = "674", mask = "###-####"),
    CountryDetails(name = "Nepal", flagCode = "np", countryCode = "977", mask = "##-###-###"),
    CountryDetails(name = "Nicarágua", flagCode = "ni", countryCode = "505", mask = "####-####"),
    CountryDetails(name = "Níger", flagCode = "ne", countryCode = "227", mask = "##-##-####"),
    CountryDetails(name = "Nigéria", flagCode = "ng", countryCode = "234"),
    CountryDetails(name = "Noruega", flagCode = "no", countryCode = "47", mask = "(###)##-###"),
    CountryDetails(name = "Nova Zelândia", flagCode = "nz", countryCode = "64"),
    CountryDetails(name = "Omã", flagCode = "om", countryCode = "968", mask = "##-###-###"),
    CountryDetails(name = "Palau", flagCode = "pw", countryCode = "680", mask = "###-####"),
    CountryDetails(name = "Panamá", flagCode = "pa", countryCode = "507", mask = "###-####"),
    CountryDetails(name = "Papua-Nova Guiné", flagCode = "pg", countryCode = "675", mask = "(###)##-###"),
    CountryDetails(name = "Paquistão", flagCode = "pk", countryCode = "92", mask = "(###)###-####"),
    CountryDetails(name = "Paraguai", flagCode = "py", countryCode = "595", mask = "(###)###-###"),
    CountryDetails(name = "Peru", flagCode = "pe", countryCode = "51", mask = "(###)###-###"),
    CountryDetails(name = "Polônia", flagCode = "pl", countryCode = "48", mask = "(###)###-###"),
    CountryDetails(name = "Portugal", flagCode = "pt", countryCode = "351", mask = "##-###-####"),
    CountryDetails(name = "Qatar", flagCode = "qa", countryCode = "974", mask = "####-####"),
    CountryDetails(name = "Quênia", flagCode = "ke", countryCode = "254", mask = "###-######"),
    CountryDetails(name = "Reino Unido", flagCode = "gb", countryCode = "44", mask = "##-####-####"),
    CountryDetails(name = "República Centro-Africana", flagCode = "cf", countryCode = "236", mask = "##-##-####"),
    CountryDetails(name = "República Dominicana", flagCode = "do", countryCode = "1-809"),
    CountryDetails(name = "Romênia", flagCode = "ro", countryCode = "40", mask = "##-###-####"),
    CountryDetails(name = "Ruanda", flagCode = "rw", countryCode = "250", mask = "(###)###-###"),
    CountryDetails(name = "Rússia", flagCode = "ru", countryCode = "7", mask = "(###)###-##-##"),
    CountryDetails(name = "Samoa", flagCode = "ws", countryCode = "685", mask = "##-####"),
    CountryDetails(name = "Santa Lúcia", flagCode = "lc", countryCode = "1-758", mask = "###-####"),
    CountryDetails(name = "São Cristóvão e Nevis", flagCode = "kn", countryCode = "1-869", mask = "###-####"),
    CountryDetails(name = "São Marino", flagCode = "sm", countryCode = "378", mask = "####-######"),
    CountryDetails(name = "São Tomé e Príncipe", flagCode = "st", countryCode = "239", mask = "##-#####"),
    CountryDetails(name = "São Vicente e Granadinas", flagCode = "vc", countryCode = "1-784", mask = ""),
    CountryDetails(name = "Seicheles", flagCode = "sc", countryCode = "248", mask = "###-####"),
    CountryDetails(name = "Senegal", flagCode = "sn", countryCode = "221", mask = "##-###-####"),
    CountryDetails(name = "Serra Leoa", flagCode = "sl", countryCode = "232", mask = "##-######"),
    CountryDetails(name = "Sérvia", flagCode = "rs", countryCode = "381", mask = "##-###-####"),
    CountryDetails(name = "Singapura", flagCode = "sg", countryCode = "65", mask = "####-####"),
    CountryDetails(name = "Síria", flagCode = "sy", countryCode = "963", mask = "##-####-###"),
    CountryDetails(name = "Somália", flagCode = "so", countryCode = "252", mask = "#-###-###"),
    CountryDetails(name = "Sri Lanka", flagCode = "lk", countryCode = "94", mask = "##-###-####"),
    CountryDetails(name = "Suazilândia", flagCode = "sz", countryCode = "268", mask = "##-##-####"),
    CountryDetails(name = "Sudão", flagCode = "sd", countryCode = "249", mask = "##-###-####"),
    CountryDetails(name = "Sudão do Sul", flagCode = "ss", countryCode = "211", mask = "##-###-####"),
    CountryDetails(name = "Suécia", flagCode = "se", countryCode = "46", mask = "##-###-####"),
    CountryDetails(name = "Suíça", flagCode = "ch", countryCode = "41", mask = "##-###-####"),
    CountryDetails(name = "Suriname", flagCode = "sr", countryCode = "597"),
    CountryDetails(name = "Tailândia", flagCode = "th", countryCode = "66", mask = "##-###-####"),
    CountryDetails(name = "Taiwan", flagCode = "tw", countryCode = "886"),
    CountryDetails(name = "Tajiquistão", flagCode = "tj", countryCode = "992", mask = "##-###-####"),
    CountryDetails(name = "Tanzânia", flagCode = "tz", countryCode = "255", mask = "##-###-####"),
    CountryDetails(name = "Timor-Leste", flagCode = "tl", countryCode = "670", mask = "###-#####"),
    CountryDetails(name = "Togo", flagCode = "tg", countryCode = "228", mask = "##-###-###"),
    CountryDetails(name = "Tonga", flagCode = "to", countryCode = "676", mask = "#####"),
    CountryDetails(name = "Trinidad e Tobago", flagCode = "tt", countryCode = "1-868", mask = "###-####"),
    CountryDetails(name = "Tunísia", flagCode = "tn", countryCode = "216", mask = "##-###-###"),
    CountryDetails(name = "Turcomenistão", flagCode = "tm", countryCode = "993", mask = "#-###-####"),
    CountryDetails(name = "Turquia", flagCode = "tr", countryCode = "90", mask = "(###)###-####"),
    CountryDetails(name = "Tuvalu", flagCode = "tv", countryCode = "688", mask = "######"),
    CountryDetails(name = "Ucrânia", flagCode = "ua", countryCode = "380", mask = "(##)###-##-##"),
    CountryDetails(name = "Uganda", flagCode = "ug", countryCode = "256", mask = "(###)###-###"),
    CountryDetails(name = "Uruguai", flagCode = "uy", countryCode = "598", mask = "#-###-##-##"),
    CountryDetails(name = "Uzbequistão", flagCode = "uz", countryCode = "998", mask = "##-###-####"),
    CountryDetails(name = "Vanuatu", flagCode = "vu", countryCode = "678"),
    CountryDetails(name = "Vaticano", flagCode = "va", countryCode = "379"),
    CountryDetails(name = "Venezuela", flagCode = "ve", countryCode = "58", mask = "(###)###-####"),
    CountryDetails(name = "Vietnã", flagCode = "vn", countryCode = "84"),
    CountryDetails(name = "Zâmbia", flagCode = "zm", countryCode = "260", mask = "##-###-####"),
    CountryDetails(name = "Zimbábue", flagCode = "zw", countryCode = "263", mask = "#-######"),
)