package com.kansha.redirectNow.domain

import com.kansha.redirectNow.data.model.Country

val countryList = listOf(
    Country(name = "Afeganistão", nameCode = "af", countryCode = "93"),
    Country(name = "África do Sul", nameCode = "za", countryCode = "27"),
    Country(name = "Albânia", nameCode = "al", countryCode = "355"),
    Country(name = "Alemanha", nameCode = "de", countryCode = "49"),
    Country(name = "Andorra", nameCode = "ad", countryCode = "376"),
    Country(name = "Angola", nameCode = "ao", countryCode = "244"),
    Country(name = "Antígua e Barbuda", nameCode = "ag", countryCode = "1-268"),
    Country(name = "Arábia Saudita", nameCode = "sa", countryCode = "966"),
    Country(name = "Argélia", nameCode = "dz", countryCode = "213"),
    Country(name = "Argentina", nameCode = "ar", countryCode = "54"),
    Country(name = "Armênia", nameCode = "am", countryCode = "374"),
    Country(name = "Austrália", nameCode = "au", countryCode = "61"),
    Country(name = "Áustria", nameCode = "at", countryCode = "43"),
    Country(name = "Azerbaijão", nameCode = "az", countryCode = "994"),
    Country(name = "Bahamas", nameCode = "bs", countryCode = "1-242"),
    Country(name = "Bahrein", nameCode = "bh", countryCode = "973"),
    Country(name = "Bangladesh", nameCode = "bd", countryCode = "880"),
    Country(name = "Barbados", nameCode = "bb", countryCode = "1-246"),
    Country(name = "Belarus", nameCode = "by", countryCode = "375"),
    Country(name = "Bélgica", nameCode = "be", countryCode = "32"),
    Country(name = "Belize", nameCode = "bz", countryCode = "501"),
    Country(name = "Benin", nameCode = "bj", countryCode = "229"),
    Country(name = "Bermudas", nameCode = "bm", countryCode = "1-441"),
    Country(name = "Bolívia", nameCode = "bo", countryCode = "591"),
    Country(name = "Bósnia e Herzegovina", nameCode = "ba", countryCode = "387"),
    Country(name = "Botsuana", nameCode = "bw", countryCode = "267"),
    Country(name = "Brasil", nameCode = "br", countryCode = "55"),
    Country(name = "Brunei", nameCode = "bn", countryCode = "673"),
    Country(name = "Bulgária", nameCode = "bg", countryCode = "359"),
    Country(name = "Burquina Faso", nameCode = "bf", countryCode = "226"),
    Country(name = "Burundi", nameCode = "bi", countryCode = "257"),
    Country(name = "Butão", nameCode = "bt", countryCode = "975"),
    Country(name = "Cabo Verde", nameCode = "cv", countryCode = "238"),
    Country(name = "Camarões", nameCode = "cm", countryCode = "237"),
    Country(name = "Camboja", nameCode = "kh", countryCode = "855"),
    Country(name = "Canadá", nameCode = "ca", countryCode = "1"),
    Country(name = "Catar", nameCode = "qa", countryCode = "974"),
    Country(name = "Cazaquistão", nameCode = "kz", countryCode = "7"),
    Country(name = "Chade", nameCode = "td", countryCode = "235"),
    Country(name = "Chile", nameCode = "cl", countryCode = "56"),
    Country(name = "China", nameCode = "cn", countryCode = "86"),
    Country(name = "Chipre", nameCode = "cy", countryCode = "357"),
    Country(name = "Colômbia", nameCode = "co", countryCode = "57"),
    Country(name = "Comores", nameCode = "km", countryCode = "269"),
    Country(name = "Congo", nameCode = "cg", countryCode = "242"),
    Country(name = "Coreia do Norte", nameCode = "kp", countryCode = "850"),
    Country(name = "Coreia do Sul", nameCode = "kr", countryCode = "82"),
    Country(name = "Costa do Marfim", nameCode = "ci", countryCode = "225"),
    Country(name = "Costa Rica", nameCode = "cr", countryCode = "506"),
    Country(name = "Croácia", nameCode = "hr", countryCode = "385"),
    Country(name = "Cuba", nameCode = "cu", countryCode = "53"),
    Country(name = "Dinamarca", nameCode = "dk", countryCode = "45"),
    Country(name = "Djibouti", nameCode = "dj", countryCode = "253"),
    Country(name = "Dominica", nameCode = "dm", countryCode = "1-767"),
    Country(name = "Egito", nameCode = "eg", countryCode = "20"),
    Country(name = "El Salvador", nameCode = "sv", countryCode = "503"),
    Country(name = "Emirados Árabes Unidos", nameCode = "ae", countryCode = "971"),
    Country(name = "Equador", nameCode = "ec", countryCode = "593"),
    Country(name = "Eritreia", nameCode = "er", countryCode = "291"),
    Country(name = "Eslováquia", nameCode = "sk", countryCode = "421"),
    Country(name = "Eslovênia", nameCode = "si", countryCode = "386"),
    Country(name = "Espanha", nameCode = "es", countryCode = "34"),
    Country(name = "Estados Unidos", nameCode = "us", countryCode = "1"),
    Country(name = "Estônia", nameCode = "ee", countryCode = "372"),
    Country(name = "Eswatini", nameCode = "sz", countryCode = "268"),
    Country(name = "Etiópia", nameCode = "et", countryCode = "251"),
    Country(name = "Fiji", nameCode = "fj", countryCode = "679"),
    Country(name = "Filipinas", nameCode = "ph", countryCode = "63"),
    Country(name = "Finlândia", nameCode = "fi", countryCode = "358"),
    Country(name = "França", nameCode = "fr", countryCode = "33"),
    Country(name = "Gabão", nameCode = "ga", countryCode = "241"),
    Country(name = "Gâmbia", nameCode = "gm", countryCode = "220"),
    Country(name = "Gana", nameCode = "gh", countryCode = "233"),
    Country(name = "Geórgia", nameCode = "ge", countryCode = "995"),
    Country(name = "Granada", nameCode = "gd", countryCode = "1-473"),
    Country(name = "Grécia", nameCode = "gr", countryCode = "30"),
    Country(name = "Guatemala", nameCode = "gt", countryCode = "502"),
    Country(name = "Guiana", nameCode = "gy", countryCode = "592"),
    Country(name = "Guiné", nameCode = "gn", countryCode = "224"),
    Country(name = "Guiné-Bissau", nameCode = "gw", countryCode = "245"),
    Country(name = "Guiné Equatorial", nameCode = "gq", countryCode = "240"),
    Country(name = "Haiti", nameCode = "ht", countryCode = "509"),
    Country(name = "Holanda", nameCode = "nl", countryCode = "31"),
    Country(name = "Honduras", nameCode = "hn", countryCode = "504"),
    Country(name = "Hungria", nameCode = "hu", countryCode = "36"),
    Country(name = "Iêmen", nameCode = "ye", countryCode = "967"),
    Country(name = "Ilhas Marshall", nameCode = "mh", countryCode = "692"),
    Country(name = "Índia", nameCode = "in", countryCode = "91"),
    Country(name = "Indonésia", nameCode = "id", countryCode = "62"),
    Country(name = "Irã", nameCode = "ir", countryCode = "98"),
    Country(name = "Iraque", nameCode = "iq", countryCode = "964"),
    Country(name = "Irlanda", nameCode = "ie", countryCode = "353"),
    Country(name = "Islândia", nameCode = "is", countryCode = "354"),
    Country(name = "Israel", nameCode = "il", countryCode = "972"),
    Country(name = "Itália", nameCode = "it", countryCode = "39"),
    Country(name = "Jamaica", nameCode = "jm", countryCode = "1-876"),
    Country(name = "Japão", nameCode = "jp", countryCode = "81"),
    Country(name = "Jordânia", nameCode = "jo", countryCode = "962"),
    Country(name = "Kiribati", nameCode = "ki", countryCode = "686"),
    Country(name = "Kuwait", nameCode = "kw", countryCode = "965"),
    Country(name = "Laos", nameCode = "la", countryCode = "856"),
    Country(name = "Lesoto", nameCode = "ls", countryCode = "266"),
    Country(name = "Letônia", nameCode = "lv", countryCode = "371"),
    Country(name = "Líbano", nameCode = "lb", countryCode = "961"),
    Country(name = "Libéria", nameCode = "lr", countryCode = "231"),
    Country(name = "Líbia", nameCode = "ly", countryCode = "218"),
    Country(name = "Liechtenstein", nameCode = "li", countryCode = "423"),
    Country(name = "Lituânia", nameCode = "lt", countryCode = "370"),
    Country(name = "Luxemburgo", nameCode = "lu", countryCode = "352"),
    Country(name = "Madagascar", nameCode = "mg", countryCode = "261"),
    Country(name = "Malásia", nameCode = "my", countryCode = "60"),
    Country(name = "Malawi", nameCode = "mw", countryCode = "265"),
    Country(name = "Maldivas", nameCode = "mv", countryCode = "960"),
    Country(name = "Mali", nameCode = "ml", countryCode = "223"),
    Country(name = "Malta", nameCode = "mt", countryCode = "356"),
    Country(name = "Marrocos", nameCode = "ma", countryCode = "212"),
    Country(name = "Maurício", nameCode = "mu", countryCode = "230"),
    Country(name = "Mauritânia", nameCode = "mr", countryCode = "222"),
    Country(name = "México", nameCode = "mx", countryCode = "52"),
    Country(name = "Mianmar", nameCode = "mm", countryCode = "95"),
    Country(name = "Micronésia", nameCode = "fm", countryCode = "691"),
    Country(name = "Moçambique", nameCode = "mz", countryCode = "258"),
    Country(name = "Moldávia", nameCode = "md", countryCode = "373"),
    Country(name = "Mônaco", nameCode = "mc", countryCode = "377"),
    Country(name = "Mongólia", nameCode = "mn", countryCode = "976"),
    Country(name = "Montenegro", nameCode = "me", countryCode = "382"),
    Country(name = "Namíbia", nameCode = "na", countryCode = "264"),
    Country(name = "Nauru", nameCode = "nr", countryCode = "674"),
    Country(name = "Nepal", nameCode = "np", countryCode = "977"),
    Country(name = "Nicarágua", nameCode = "ni", countryCode = "505"),
    Country(name = "Níger", nameCode = "ne", countryCode = "227"),
    Country(name = "Nigéria", nameCode = "ng", countryCode = "234"),
    Country(name = "Noruega", nameCode = "no", countryCode = "47"),
    Country(name = "Nova Zelândia", nameCode = "nz", countryCode = "64"),
    Country(name = "Omã", nameCode = "om", countryCode = "968"),
    Country(name = "Palau", nameCode = "pw", countryCode = "680"),
    Country(name = "Panamá", nameCode = "pa", countryCode = "507"),
    Country(name = "Papua-Nova Guiné", nameCode = "pg", countryCode = "675"),
    Country(name = "Paquistão", nameCode = "pk", countryCode = "92"),
    Country(name = "Paraguai", nameCode = "py", countryCode = "595"),
    Country(name = "Peru", nameCode = "pe", countryCode = "51"),
    Country(name = "Polônia", nameCode = "pl", countryCode = "48"),
    Country(name = "Portugal", nameCode = "pt", countryCode = "351"),
    Country(name = "Qatar", nameCode = "qa", countryCode = "974"),
    Country(name = "Quênia", nameCode = "ke", countryCode = "254"),
    Country(name = "Reino Unido", nameCode = "gb", countryCode = "44"),
    Country(name = "República Centro-Africana", nameCode = "cf", countryCode = "236"),
    Country(name = "República Dominicana", nameCode = "do", countryCode = "1-809"),
    Country(name = "Romênia", nameCode = "ro", countryCode = "40"),
    Country(name = "Ruanda", nameCode = "rw", countryCode = "250"),
    Country(name = "Rússia", nameCode = "ru", countryCode = "7"),
    Country(name = "Samoa", nameCode = "ws", countryCode = "685"),
    Country(name = "Santa Lúcia", nameCode = "lc", countryCode = "1-758"),
    Country(name = "São Cristóvão e Nevis", nameCode = "kn", countryCode = "1-869"),
    Country(name = "São Marino", nameCode = "sm", countryCode = "378"),
    Country(name = "São Tomé e Príncipe", nameCode = "st", countryCode = "239"),
    Country(name = "São Vicente e Granadinas", nameCode = "vc", countryCode = "1-784"),
    Country(name = "Seicheles", nameCode = "sc", countryCode = "248"),
    Country(name = "Senegal", nameCode = "sn", countryCode = "221"),
    Country(name = "Serra Leoa", nameCode = "sl", countryCode = "232"),
    Country(name = "Sérvia", nameCode = "rs", countryCode = "381"),
    Country(name = "Singapura", nameCode = "sg", countryCode = "65"),
    Country(name = "Síria", nameCode = "sy", countryCode = "963"),
    Country(name = "Somália", nameCode = "so", countryCode = "252"),
    Country(name = "Sri Lanka", nameCode = "lk", countryCode = "94"),
    Country(name = "Suazilândia", nameCode = "sz", countryCode = "268"),
    Country(name = "Sudão", nameCode = "sd", countryCode = "249"),
    Country(name = "Sudão do Sul", nameCode = "ss", countryCode = "211"),
    Country(name = "Suécia", nameCode = "se", countryCode = "46"),
    Country(name = "Suíça", nameCode = "ch", countryCode = "41"),
    Country(name = "Suriname", nameCode = "sr", countryCode = "597"),
    Country(name = "Tailândia", nameCode = "th", countryCode = "66"),
    Country(name = "Taiwan", nameCode = "tw", countryCode = "886"),
    Country(name = "Tajiquistão", nameCode = "tj", countryCode = "992"),
    Country(name = "Tanzânia", nameCode = "tz", countryCode = "255"),
    Country(name = "Timor-Leste", nameCode = "tl", countryCode = "670"),
    Country(name = "Togo", nameCode = "tg", countryCode = "228"),
    Country(name = "Tonga", nameCode = "to", countryCode = "676"),
    Country(name = "Trinidad e Tobago", nameCode = "tt", countryCode = "1-868"),
    Country(name = "Tunísia", nameCode = "tn", countryCode = "216"),
    Country(name = "Turcomenistão", nameCode = "tm", countryCode = "993"),
    Country(name = "Turquia", nameCode = "tr", countryCode = "90"),
    Country(name = "Tuvalu", nameCode = "tv", countryCode = "688"),
    Country(name = "Ucrânia", nameCode = "ua", countryCode = "380"),
    Country(name = "Uganda", nameCode = "ug", countryCode = "256"),
    Country(name = "Uruguai", nameCode = "uy", countryCode = "598"),
    Country(name = "Uzbequistão", nameCode = "uz", countryCode = "998"),
    Country(name = "Vanuatu", nameCode = "vu", countryCode = "678"),
    Country(name = "Vaticano", nameCode = "va", countryCode = "379"),
    Country(name = "Venezuela", nameCode = "ve", countryCode = "58"),
    Country(name = "Vietnã", nameCode = "vn", countryCode = "84"),
    Country(name = "Zâmbia", nameCode = "zm", countryCode = "260"),
    Country(name = "Zimbábue", nameCode = "zw", countryCode = "263"),
)